### ISSUE TITLE
Draft reviews & feedback

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Hybrid-identity#1]
Please leave your review comments for our author below.

**Comment by JoshuaL1** [comment]
Should an issue be created for each problem item or will a summary in this thread work?

**Comment by polichtm** [comment]
Hi Joshua
ideally, pls create a pull request that includes the change you are suggesting
rgds
Marcin

**Comment by JoshuaL1** [comment]
@Marcin, will attempt to do this, but will have a running list in a word document in the event I'm unable to get this done. Thanks for the guidance.

**Comment by JoshuaL1** [comment]
@polichtm will attempt to do this, however will keep a word document as a backup in the event I am unsuccessful (Pull request is currently disabled for me). -Josh

**Comment by JoshuaL1** [comment]
### Before Hands On Lab Feedback### 
Task 5.2 (Lines 176-183): IE enhanced configuration was not disabled by script, had to go into GUI, turn it back on and off.
Task 6.2(Line 222): further clarification may be needed that there is an “attachments dialog”, I  did not see the .csv at first, only the blue icon for the .ps1
Task 6.4 (Line 224): Before running this, should there be some documentation to indicate to enable running of unsigned scripts? Either by Set-ExecutionPolicy -ExecutionPolicy Bypass or other method (ISE must be ran as admin). 
Task 6.4 (Line 224): Script is set to create random users from CSV (line 154 in .ps1 file), this creates errors with 6.5 (Line 226) and other subsequent steps where a specific user is called out.

**Comment by rdendtler** [comment]
General comments
Overall, I love this content. I need to carve out a full day to run through the labs a few times myself. 

1. 1. We have a lot of things we're trying to do in this overall set of labs.  Recommend we take the learning objectives and put them in a separate doc and link, or something similar.  In the HOL (and other places) we list out 22 learning objectives.  This one is complex...how about we create a doc of the learning objectives (and index kinda) and link back to the tasks that address them.. This will reduce the size and complexty of the HOL and other docs
2. 2.  Example, in Exercise 1 of HOL, Overview 1 becomes a "wall of words"...  We need to pull this out as mentioned above
3. In HOL where we configure AD Connect, we use Pass-Through (yay!!).. we should provide a note to the decision tree on the other options.  
4. Can we provide a picture of the overall solution architecture (in HOL, but used elsewhere too)
5. Whiteboard Session: Trainer Guide presentation.. This is a wall of text.. I know we're going over a LOT of stuff...and it's clear you were trying to minimize, can we find a way to reduce the text in slides 4-13?  Also, font size changes between slides. Let's normalize.
6.  We probably will adjust after this is delieverd a few times, but looking at the Whiteboard session, I realize just how much we are asking students to do in a 60m session.  I'm not sure we have enough time.  Should we reduce scope on the WB session to give more time?
7.  Slides 29-63 are too much text.. Recommend we put this on the MCW as a Markdown file (well, it's already in student/trainer guide) and have them read it from there.  We should simplify the slides a bit..

**Comment by JoshuaL1** [comment]
### HOL step by step feedback
Exercise 1
Task 1.9 (Line 182) : On the Contoso - Licenses, blade, select All Products click + Try/Buy. 
Line 186: Perhaps add a note that it may take a few minutes for the trial to be activated (took about 5 in my run-through)
Task 5.9 (Line 392)- user accounts don’t match due to user creation script selecting random user objects from CSV
Task 6.1 (Line 406) – Redundant due to pre-requisites?
Task 6.7 (line 420), point of clarification: In the Azure portal, search for and select Azure Active Directory and navigate to the Contoso - Overview blade.
Task 6.23 (Line 466) - We had discussed enabling Password Synchronization for redundancy and the benefit of having a backup if PTA fails (this also enhances Identity Protection.)
Task 11.3 (Line 691)- Due to issue noted for the user creation, AGAYERS was not added to Engineering group and therefore did not get it’s UPN changed to the verified domain.
Exercise 2
Task 5.9 (Line 983)- when using Custom Banned Password list, each word should be on its own line (no commas)
Task 5.13 (Line 995)- Ran ISE as standard user and received error, Ran ISE as an Admin
Task 9.30 (Line 1206)- Due to user creation issue, name does not match desired activity
Task 10.13 (Line 1273)- Due to user creation issue, name does not match desired activity (also a typo on “additional”)
Exercise 3
Task 2.16 (Line 1436)- Receiving the following error when attempting this step: The following Active Directory Domain Services error occurred: the server is unwilling to process the request.
Task 3.2 (Line 1449) Due to user creation issue, name does not match desired activity 
Task 4.8 (Line 1486)- On the Fabrikam - Overview blade, click Licenses.
Task 4.9 (Line 1487) - On the Fabrikam - Licenses, blade, select All Products click + Try/Buy
After the Hands-On Lab
Task 1.1 (Line 1778)- Should the purchased custom domain should be removed from the contoso tenant if client wants to re-use?

**Comment by polichtm** [comment]
Hi Rob,
Could you advise how you envision “a picture of the overall solution architecture” in this case?

Rgds
Marcin

**Comment by polichtm** [comment]
Hi Josh,
These have been addressed in the most recent update

thnx
Marcin

**Comment by polichtm** [comment]
Hi Josh,
Updated – my comments inline

Thnx
Marcin

**Comment by DawnmarieDesJardins** [comment]
Closing this issue with the publish of the workshop
