### ISSUE TITLE
Hands on and before hands on

### ISSUE THREAD

**Issue by PrernaNagori09** [microsoft/MCW-Hybrid-identity#9]
#1:   Exercise-1-> Task-11- Perform Hybrid Azure AD join- > Step-3
![1](https://user-images.githubusercontent.com/56402513/76414332-17f32180-63bd-11ea-9785-28b67033b3d1.png)

Problem:  AGAyers does not have remote desktop rights to login to APP1 Server.

Recommendation :
Update AD scripts to add the user to “Remote Desktop Users” AD Group or add instructions in the lab guide to add user the remote desktop users group manually

#2:   Exercise-2 - Task-10- Implement Azure AD Privileged Identity Management
![2](https://user-images.githubusercontent.com/56402513/76414342-1d506c00-63bd-11ea-9f96-691c1399996a.png)

Problem: This user(AGAyers) is not a member of the Engineering group. As per documentation, we are allowing access to the “Engineering” group only.

![2 1](https://user-images.githubusercontent.com/56402513/76414815-10804800-63be-11ea-8f99-7e1f3211d4ff.png)

Recommendation.: Please update scripts to include AGAyers to Engineering Group, or update the documentation to use the correct user who is part of Engineering.

#3, Exercise 3:- Configure application access in hybrid scenarios - Task-6:- 
Problem: Email-address value highlighted in below screenshot needs to be generalized. 

![3](https://user-images.githubusercontent.com/56402513/76414822-17a75600-63be-11ea-92c7-1ebc2db50ab4.png)

Recommendation:- use jane.doe@< Fabrikam-Domain-name>

**Comment by PrernaNagori09** [comment]
Any update on this.

**Comment by paulopsgility** [comment]
We'll take a look at it.

**Comment by paulopsgility** [comment]
I just ran through the lab to this point and everything worked fine so I am going to close this out for now. There are many steps that could go wrong but I don't see any place where it would break your ability to login. 

I would suggest validating the account can login to APP1 after the Before the Hands On Lab section to make sure you did everything correctly. As you pointed out, we run that script to setup that account in that section. It seems to work fine. If it works then, then stops working later, then you know you did something wrong downstream of that. 

Also, on group membership, you can validate this from DC1 at the end of the Before the Hands-On Lab section. Just look in Active Directory Users and Computers, expand contoso.local, then expand Demo Accounts, then expand Groups and there you will see the Engineering group. If your agayers account isn't there then go check the output of your PowerShell scripts because something went wrong.
